version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    pip:
      patterns:
        - "*"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    docker:
      patterns:
        - "*"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    github-actions:
      patterns:
        - "*"
  open-pull-requests-limit: 10
