services:
  db:
    image: postgres:bullseye
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laa_assess_non_standard_magistrate_fee_production
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://appuser:my_password@host.docker.internal:5432/laa_assess_non_standard_magistrate_fee_production
      RACK_ENV: production
      RAILS_ENV: production
      SECRET_KEY_BASE: test1234
      RAILS_LOG_TO_STDOUT: enabled
    depends_on:
      - db
networks:
  default:
    name: assess_nsm
