apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-crime-application-store.fullname" . }}-worker
  labels:
    {{- include "laa-crime-application-store.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.worker }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: {{ include "laa-crime-application-store.fullname" . }}-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "laa-crime-application-store.fullname" . }}-worker
        metrics-target: {{ include "laa-crime-application-store.fullname" . }}-metrics-target
    spec:
      {{ if .Values.service_account.required }}
      serviceAccountName: {{ .Values.service_account.name }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- include "laa-crime-application-store.defaultSecurityContext" . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bundle
            - exec
            - sidekiq
          # SidekiqAlive runs on port 7433 to allow health checking
          ports:
            - name: http
              containerPort: 7433
              protocol: TCP
            - containerPort: 9394
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket-output
                  key: bucket_name
          {{ if .Values.postgresql.enabled }}
            - name: POSTGRES_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.postgresPassword }}
            - name: POSTGRES_HOSTNAME
              value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}
            - name: POSTGRES_NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: DATABASE_SSLMODE
              value: 'prefer'
          {{ else }}
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password
            - name: POSTGRES_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_address
          {{ end }}
            - name: APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: app_client_id
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: tenant_id
            {{- if not (eq .Values.environment "prod") }}
            - name: AUTHENTICATION_REQUIRED
              value: {{ .Values.envVars.authenticationRequired | quote}}
            {{ end }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key_base
            - name: OS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: os_api_key
            - name: GOVUK_NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: notify_api_key
            - name: RACK_ENV
              value: 'production'
            - name: RAILS_ENV
              value: 'production'
            - name: RAILS_LOG_TO_STDOUT
              value: enabled
            - name: ENV
              value: {{ .Values.envVars.environment }}
            {{ if .Values.redis.enabled }}
            - name: REDIS_PROTOCOL
              value: "redis"
            - name: REDIS_HOST
              value: {{ template "laa-crime-application-store.redisDevHost" . }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password }}
          {{ else }}
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: crm-elasticache
                  key: primary_endpoint_address
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crm-elasticache
                  key: auth_token
          {{ end }}
            - name: ENABLE_PROMETHEUS_EXPORTER
              value: 'true'
            - name: SEND_EMAILS:
              value: 'true'
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
