kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "laa-crime-application-store.fullname" . }}-allow-prometheus-scraping-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laa-crime-application-store.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      metrics-target: {{ include "laa-crime-application-store.fullname" . }}-metrics-target
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            component: monitoring
