{{- if .Values.metabase.enabled }}
{{- $fullName := include "laa-crime-application-store.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-metabase
  namespace: {{ .Values.metabase.ingress.namespace}}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $fullName }}-metabase-{{ .Values.metabase.ingress.namespace}}-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyNoFilesLimit 524288
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6"
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - {{ .Values.metabase.url }}
      secretName: {{ .Values.metabase.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.metabase.url }}
    http:
      paths:
        - path: "/"
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}-metabase
              port:
                number: {{ .Values.metabase.service.port}}
{{- end }}

