{{- if .Values.metabase.enabled }}
{{- $fullName := include "laa-crime-application-store.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-metabase
  namespace: {{ .Values.metabase.ingress.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "laa-crime-application-store.metabase.whitelist" $ }}"
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $fullName }}-metabase-{{ .Values.metabase.ingress.namespace}}-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyNoFilesLimit 524288
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-forms-team"
      SecDefaultAction "phase:4,pass,log,tag:github_team=laa-crime-forms-team"
      SecRuleRemoveById 920120
      SecRuleRemoveById 921110
      SecRuleRemoveById 933210
      SecRuleRemoveById 942230
      SecRuleRemoveById 951120
      SecRuleRemoveById 951220
      SecRuleRemoveById 952100
      SecRule TIME_HOUR "!@pm 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20" \
        "id:998,phase:1,deny,status:503,tag:github_team=laa-crime-forms-team"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=15"
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - {{ .Values.metabase.url }}
      secretName: {{ .Values.metabase.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.metabase.url }}
    http:
      paths:
        - path: "/"
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}-metabase
              port:
                number: {{ .Values.metabase.service.port}}
{{- end }}

