{{- if .Values.metabase.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_deploy.fullname" . }}-metabase
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3000
  selector:
    app: {{ include "helm_deploy.fullname" . }}-metabase
{{- end }}
