{
 "title": "LAA non-standard crime claims / Provider sidekiq metrics",
 "description": "Visual Sidekiq Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_stats_processed{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_stats_failed{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_process_busy{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Enqueued",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_stats_enqueued{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_stats_retry_size{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_stats_scheduled_size{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Dead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ruby_sidekiq_stats_dead_size{namespace=\"$namespace\",pod=~\"laa-.+-app-.+\"})"
    }
   ]
  },
  {
   "title": "Jobs processed every second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_sidekiq_jobs_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "All jobs"
    },
    {
     "expr": "sum(rate(ruby_sidekiq_failed_jobs_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Failed jobs"
    }
   ]
  },
  {
   "title": "Number of jobs actively being processed",
   "type": "graph",
   "description": "Number of jobs waiting in queues to be executed",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_sidekiq_stats_workers_size{namespace=\"$namespace\"})",
     "legendFormat": "Jobs being processed"
    }
   ]
  }
 ]
}