{
 "title": "LAA non-standard crime claims / Rails metrics",
 "tags": [
  "NSCC",
  "rails"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ruby_rss,namespace)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(ruby_http_requests_total{namespace=\"$namespace\"},controller)"
    }
   },
   {
    "name": "action",
    "query": {
     "query": "label_values(ruby_http_requests_total{namespace=\"$namespace\",controller=~\"$controller\"},action)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Web Workers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ruby_rss{type=~'master|web|worker',namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests / h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[60m]) * 60 * 60)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Avg Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (controller,action) (rate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m])  > 0)\n/\navg by (controller,action) (rate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) > 0) * 1000",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Request Count / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller, action) (rate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\", controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Max Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Max Request",
     "target": "carbon.*"
    },
    {
     "expr": "max(rate(ruby_http_request_sql_duration_seconds_sum{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_sql_duration_seconds_count{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Max SQL"
    }
   ]
  },
  {
   "title": "Successful Requests / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=\"$namespace\",status=~\"^[23].*\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Avg Request"
    },
    {
     "expr": "avg(rate(ruby_http_request_sql_duration_seconds_sum{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_sql_duration_seconds_count{namespace=\"$namespace\",controller!~'.*health',controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Avg SQL"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=\"$namespace\",status=~\"^[45].*\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Slow Actions",
   "type": "table",
   "description": "Top 10 slowest requests over a one week period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,avg(rate(ruby_http_request_duration_seconds_sum{namespace=~\"$namespace\"}[1w]) / rate(ruby_http_request_duration_seconds_count{namespace=~\"$namespace\"}[1w])) by (controller, action)) \n"
    }
   ]
  },
  {
   "title": "Most Frequent Actions / Day",
   "type": "table",
   "description": "Average number of requests per day during last week",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,sum(rate(ruby_http_request_duration_seconds_count{namespace=~\"$namespace\",controller!~'.*health'}[1w]) * 3600 * 24) by (controller, action))"
    }
   ]
  },
  {
   "title": "ActiveRecord Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_active_record_connection_pool_size{namespace=\"$namespace\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum(ruby_active_record_connection_pool_connections{namespace=\"$namespace\"})",
     "legendFormat": "Pool Connections"
    },
    {
     "expr": "sum(ruby_active_record_connection_pool_busy{namespace=\"$namespace\"})",
     "legendFormat": "Busy Connections"
    },
    {
     "expr": "sum(ruby_active_record_connection_pool_dead{namespace=\"$namespace\"})",
     "legendFormat": "Dead Connections"
    },
    {
     "expr": "sum(ruby_active_record_connection_pool_waiting{namespace=\"$namespace\"})",
     "legendFormat": "Waiting Connections"
    }
   ]
  },
  {
   "title": "Puma Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_puma_max_threads{namespace=\"$namespace\"})",
     "legendFormat": "Max Threads"
    },
    {
     "expr": "sum(ruby_puma_thread_pool_capacity{namespace=\"$namespace\"})",
     "legendFormat": "Pool Capacity"
    },
    {
     "expr": "sum(ruby_puma_running_threads{namespace=\"$namespace\"})",
     "legendFormat": "Running Threads"
    },
    {
     "expr": "sum(ruby_puma_request_backlog{namespace=\"$namespace\"})",
     "legendFormat": "Request Backlog"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ruby_rss{namespace=~\"$namespace\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Object Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(ruby_allocated_objects_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Heap Web",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(ruby_heap_free_slots{namespace=\"$namespace\",type=~\"master|web|worker\"}) without (namespace)",
     "legendFormat": "Min Free Slots {{type}}"
    },
    {
     "expr": "max(ruby_heap_live_slots{namespace=\"$namespace\",type=~\"master|web|worker\"}) without (namespace)",
     "legendFormat": "Max Live Slots {{type}}"
    }
   ]
  }
 ]
}