version: 2.1

orbs:
  newman: postman/newman@1.0.0
  snyk: snyk/snyk@1.1.2
  aws-cli: circleci/aws-cli@4.0.0 # use v4 of this orb
  aws-ecr: circleci/aws-ecr@8.2.1 # this orb doesn't support OIDC v2, so we use aws-cli to authenticate



executors:
  cloud-platform-executor:
    docker:
      - image: ministryofjustice/cloud-platform-tools:2.3.0
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-estimate-eligibility
  linting-executor:
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          - RAILS_ENV=test
          - TZ: "Europe/London"
  build-image-executor:
    resource_class: small
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          - RAILS_ENV=test
          - TZ: "Europe/London"
  test-executor:
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          - RAILS_ENV=test
          - PGHOST=localhost
          - PGUSER=user
          - TZ: "Europe/London"
      - image: cimg/postgres:14.8
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: nscc_app_store_test
  ccq-executor:

commands:
  build-docker-image:
    steps:
      - run:
          name: Compile Docker Image
          command: |
              docker build \
                --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
                --build-arg COMMIT_ID=${CIRCLE_SHA1} \
                --build-arg BUILD_TAG="app-${CIRCLE_SHA1}" \
                --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
                --pull \
                --tag app \
                --file Dockerfile .

  deploy_to_environment:
    description: >
      Deploy image to the specified environment
    parameters:
      environment:
        description: Name of environment to deploy to
        type: string
      registry:
        description: Location of ECR Images
        type: string
        default: ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
    steps:
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - checkout
      - run:
          name: Authenticate K8s
          command: |
              echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
              kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=${K8S_CLUSTER_NAME}
              kubectl config set-credentials circleci --token=${K8S_TOKEN}
              kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_NAMESPACE}
              kubectl config use-context ${K8S_CLUSTER_NAME}
              kubectl --namespace=${K8S_NAMESPACE} get pods
      - run:
          name: Deploy to namespace
          command: |
              helm upgrade laa-crime-application-store ./helm_deploy/laa-crime-application-store/. \
                  --install --wait --force \
                  --namespace=${K8S_NAMESPACE} \
                  --values ./helm_deploy/laa-crime-application-store/values-<< parameters.environment >>.yaml \
                  --set image.repository="<< parameters.registry >>/${ECR_REPOSITORY}" \
                  --set image.tag="${CIRCLE_SHA1}" \
                  --atomic

references:
  install_packages_for_testing: &install_packages_for_testing
    run:
      name: Install System packages needed for testing
      command: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client cmake

  restore_gems_cache: &restore_gems_cache
    restore_cache:
      keys:
        - nscc-app-store-gems-{{ checksum "Gemfile.lock" }}
        - nscc-app-store-gems

  install_gems: &install_gems
    run:
      name: Install ruby gems
      command: |
        sudo gem update --system
        bundle config set --local frozen 'true'
        bundle config set --local path 'vendor/bundle'
        bundle config set --local without 'development'
        bundle install --jobs=4 && bundle clean

  save_gems_cache: &save_gems_cache
    save_cache:
      key: nscc-app-store-gems-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

  restore_helm_cache: &restore_helm_cache
    restore_cache:
      keys:
        - nscc-app-store-helm-{{ checksum "deploy/helm/Chart.lock" }}
        - nscc-app-store-helm

  save_helm_cache: &save_helm_cache
    save_cache:
      key: nscc-app-store-helm-{{ checksum "deploy/helm/Chart.lock" }}
      paths:
        - deploy/helm/charts

  setup_database: &setup_database
    run:
      name: Database Setup
      command: |
        bundle exec rake db:schema:load
        bundle exec rake db:migrate

jobs:
  lint-app:
    executor: linting-executor
    steps:
      - checkout
      - *restore_gems_cache
      - *install_gems
      - *save_gems_cache
      - run:
          name: Run Rubocop
          command:  bundle exec rubocop

  test-app:
    executor: test-executor
    steps:
      - checkout
      - *install_packages_for_testing
      - *restore_gems_cache
      - *install_gems
      - *save_gems_cache
      - *setup_database
      - run:
          name: Run ruby tests
          command: |
            bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/test-results/rspec/rspec.xml
      - store_test_results:
          path: /tmp/test-results/rspec
      - store_artifacts:
          path: ./coverage

  scan-docker-image:
    executor: build-image-executor
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - build-docker-image
      - snyk/scan:
          token-variable: SNYK_TOKEN
          docker-image-name: app
          target-file: ./Dockerfile
          organization: 'legal-aid-agency'
          project: ministryofjustice/laa-crime-application-store
          severity-threshold: "high"
          fail-on-issues: true

  build-and-push:
    executor: aws-ecr/default # use the aws-ecr/default executor to start the docker daemon
    steps:
      - checkout
      # Authenticate to AWS using OIDC v2 with the AWS CLI
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      # Authenticate to the ECR repository using the standard command
      - run: |
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
      # Build and push your Docker image
      - aws-ecr/build-image:
          push-image: true
          tag: ${CIRCLE_SHA1}
          region: $ECR_REGION # this will use the env var
          repo: $ECR_REPOSITORY # this will use the env var
          extra-build-args: |
            --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
            --build-arg BUILD_TAG=${CIRCLE_SHA1} \
            --build-arg COMMIT_ID=${CIRCLE_SHA1} \
            --build-arg APP_BRANCH=${CIRCLE_BRANCH} \

  deploy-dev:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: development

  deploy-dev-crm4:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: dev-crm4

  deploy-uat:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: uat

  deploy-prod:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: production

  postman-test:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./postman/collections/Ping.postman_collection.json
          environment: ./postman/environments/${K8S_ENV}.postman_environment.json
      - newman/newman-run:
          collection: ./postman/collections/Application.postman_collection.json
          environment: ./postman/environments/${K8S_ENV}.postman_environment.json
          additional-options: --env-var="tenantId=${ENTRA_TENANT_ID}" --env-var="applicationId=${ENTRA_APP_ID}" --env-var="applicationSecret=${ENTRA_APP_SECRET}"

workflows:
  version: 2

  test:
    jobs:
      - lint-app:
          filters:
            branches:
              ignore: main
      - test-app:
          filters:
            branches:
              ignore: main
      - scan-docker-image:
          filters:
            branches:
              ignore:
                - main

  build-push-branch:
    jobs:
      - branch-build-approval:
          type: approval
          filters:
            branches:
              ignore:
                - main
      - build-and-push:
          requires:
              - branch-build-approval
      - hold-dev:
          type: approval
          requires:
            - build-and-push
      - deploy-dev:
          context: laa-crime-application-store-dev
          requires:
            - hold-dev
      - postman-test:
          name: dev postman tests
          context: laa-crime-application-store-dev
          requires:
            - deploy-dev
      - hold-dev-crm4:
          type: approval
          requires:
            - build-and-push
      - deploy-dev-crm4:
          context: laa-crime-application-store-dev-crm4
          requires:
            - hold-dev-crm4
      - postman-test:
          name: dev-crm4 postman tests
          context: laa-crime-application-store-dev-crm4
          requires:
            - deploy-dev-crm4
      - hold-uat:
          type: approval
          requires:
            - build-and-push
      - deploy-uat:
          context: laa-crime-application-store-uat
          requires:
            - hold-uat
      - postman-test:
          name: uat postman tests
          context: laa-crime-application-store-uat
          requires:
            - deploy-uat

  test-build-deploy-main:
    jobs:
      - lint-app:
          filters:
            branches:
              only: main
      - test-app:
          filters:
            branches:
              only: main
      - scan-docker-image:
          filters:
            branches:
              only:
                - main
      - build-and-push:
          requires:
            - lint-app
            - test-app
            - scan-docker-image
      - hold-dev:
          type: approval
          requires:
            - build-and-push
      - deploy-dev:
          context: laa-crime-application-store-dev
          requires:
            - hold-dev
      - postman-test:
          name: dev postman tests
          context: laa-crime-application-store-dev
          requires:
            - deploy-dev
      - hold-dev-crm4:
          type: approval
          requires:
            - build-and-push
      - deploy-dev-crm4:
          context: laa-crime-application-store-dev-crm4
          requires:
            - hold-dev-crm4
      - postman-test:
          name: dev-crm4 postman tests
          context: laa-crime-application-store-dev-crm4
          requires:
            - deploy-dev-crm4
      - hold-uat:
          type: approval
          requires:
            - build-and-push
      - deploy-uat:
          context: laa-crime-application-store-uat
          requires:
            - hold-uat
      - postman-test:
          name: uat postman tests
          context: laa-crime-application-store-uat
          requires:
            - deploy-uat
      - hold-prod:
          type: approval
          requires:
            - build-and-push
      - deploy-prod:
          context: laa-crime-application-store-prod
          requires:
            - hold-prod
