version: 2.1

orbs:
  newman: postman/newman@1.0.0
  snyk: snyk/snyk@1.1.2
  aws-cli: circleci/aws-cli@4.1.3 # use v4 of this orb
  aws-ecr: circleci/aws-ecr@9.0.2 # this orb doesn't support OIDC v2, so we use aws-cli to authenticate

executors:
  python-build-image-executor:
    resource_class: small
    docker:
      - image: cimg/python:3.12.1

  cloud-platform-executor:
    resource_class: small
    docker:
      - image: ministryofjustice/cloud-platform-tools
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-assess-a-claim
          REPO_NAME: laa-court-data-api

  python-test-executor:
    working_directory: ~/repo/legacy_implementation
    docker:
      - image: cimg/python:3.12.1
        environment:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: circleci
          POSTGRES_NAME: laa_crime_application_store
          POSTGRES_HOSTNAME: 127.0.0.1
          TZ: Europe/London
      - image: cimg/postgres:14.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "circleci"
          POSTGRES_DB: laa_crime_application_store_test
  test-executor:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.3.0-browsers
        environment:
          RACK_ENV: test
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:circleci@127.0.0.1:5432/laa_crime_application_store_test
          TZ: Europe/London
      - image: cimg/postgres:13.12-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "circleci"
          POSTGRES_DB: laa_crime_application_store_test

commands:
  install-python-requirements:
    steps:
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - deps-{{ .Branch }}
      - run:
          name: Install Requirements
          command: pipenv install --dev

  install-requirements:
    steps:
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-bundle-
      - run:
          name: Install gems
          command: |
            bundler_version=$(cat Gemfile.lock | tail -1 | tr -d " ")
            gem install bundler -v $bundler_version
            bundle config set path 'vendor/bundle'
            bundle check || bundle install --jobs=4 --retry=3
            bundle clean --force
      - save_cache:
          key: v1-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.bundle
            - vendor/bundle

  run-python-tests:
    steps:
      - run:
          name: Run pytest
          command: pipenv run pytest --cov-report term --junitxml=test-results/junit.xml --cov=laa_crime_application_store_app tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage

  db-setup:
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: |
            RUBYOPT=-W:no-deprecated \
            bundle exec rails db:prepare --trace

  run-tests:
    steps:
      - db-setup
      - run:
          name: Run rspec tests
          command: |
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=filename)
            RUBYOPT=-W:no-deprecated \
            INCLUDE_ACCESSIBILITY_SPECS=1 \
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec/rspec.xml \
              -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results/rspec
      - run:
          name: Stash coverage results
          command: |
            mkdir coverage_results
            cp -R coverage/.resultset.json coverage_results/.resultset-${CIRCLE_NODE_INDEX}.json
      - persist_to_workspace:
          root: .
          paths:
            - coverage_results
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage

  run-python-linting:
    steps:
      - run:
          name: Check styling
          command: pipenv run flake8

  run-linting:
    steps:
      - run:
          name: Run rubocop
          command: bundle exec rubocop

  build-docker-image:
    steps:
      - run:
          name: Compile Docker Image
          command: |
              docker build \
                --build-arg APP_BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
                --build-arg APP_GIT_COMMIT=${CIRCLE_SHA1} \
                --build-arg APP_BUILD_TAG="app-${CIRCLE_SHA1}" \
                --build-arg APP_BRANCH_NAME=${CIRCLE_BRANCH} \
                --pull \
                --tag app \
                --file Dockerfile .

  deploy_to_environment:
    description: >
      Deploy image to the specified environment
    parameters:
      environment:
        description: Name of environment to deploy to
        type: string
      registry:
        description: Location of ECR Images
        type: string
        default: ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
    steps:
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - checkout
      - run:
          name: Authenticate K8s
          command: |
              echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
              kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=${K8S_CLUSTER_NAME}
              kubectl config set-credentials circleci --token=${K8S_TOKEN}
              kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_NAMESPACE}
              kubectl config use-context ${K8S_CLUSTER_NAME}
              kubectl --namespace=${K8S_NAMESPACE} get pods
      - deploy:
            name: Deploy to << parameters.environment >>
            command: |
              ./bin/deploy << parameters.environment >>

jobs:
  lint-python-app:
    working_directory: ~/repo/legacy_implementation
    executor: python-build-image-executor
    parallelism:
    steps:
      - checkout:
          path: ~/repo
      - install-python-requirements
      - run-python-linting

  lint-app:
    working_directory: ~/repo
    executor: test-executor
    parallelism:
    steps:
      - checkout
      - install-requirements
      - run-linting

  test-python-app:
    working_directory: ~/repo/legacy_implementation
    executor: python-test-executor
    parallelism: 1
    steps:
      - checkout:
          path: ~/repo
      - install-python-requirements
      - run-python-tests

  test-app:
    working_directory: ~/repo
    executor: test-executor
    parallelism: 1
    steps:
      - checkout
      - install-requirements
      - run-tests

  scan-python-docker-image:
    working_directory: ~/repo/legacy_implementation
    executor: python-build-image-executor
    parallelism: 1
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - build-docker-image
      - snyk/scan:
          token-variable: SNYK_TOKEN
          docker-image-name: app
          target-file: ./Dockerfile
          organization: 'legal-aid-agency'
          project: ministryofjustice/laa-crime-application-store
          severity-threshold: "high"
          fail-on-issues: true

  scan-docker-image:
    working_directory: ~/repo
    executor: test-executor
    parallelism: 1
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - build-docker-image
      - snyk/scan:
          token-variable: SNYK_TOKEN
          docker-image-name: app
          target-file: ./Dockerfile
          organization: 'legal-aid-agency'
          project: ministryofjustice/laa-crime-application-store
          severity-threshold: "high"
          fail-on-issues: true

  build-and-push:
    executor: aws-ecr/default # use the aws-ecr/default executor to start the docker daemon
    steps:
      - checkout
      # Authenticate to AWS using OIDC v2 with the AWS CLI
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      # Authenticate to the ECR repository using the standard command
      - run: |
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
      - run:
          name: Set ECR_TAGS environment variable for use in next step
          command: |
            [[ "$CIRCLE_BRANCH" == "main" ]] && ECR_TAGS="main-$CIRCLE_SHA1,latest" || ECR_TAGS="branch-$CIRCLE_SHA1"
            echo "export ECR_TAGS=$ECR_TAGS" >> "$BASH_ENV"
            echo "export APP_BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)" >> "$BASH_ENV"
            source "$BASH_ENV"
      # Build and push your Docker image
      - aws-ecr/build_image:
          push_image: true
          tag: ${ECR_TAGS}
          region: $ECR_REGION # this will use the env var
          repo: $ECR_REPOSITORY # this will use the env var
          account_id: $AWS_ECR_REGISTRY_ID
          extra_build_args: >-
            --build-arg APP_BUILD_DATE=${APP_BUILD_DATE}
            --build-arg APP_BUILD_TAG=${CIRCLE_SHA1}
            --build-arg APP_GIT_COMMIT=${CIRCLE_SHA1}
            --build-arg APP_BRANCH_NAME=${CIRCLE_BRANCH}

          # ========================================================================== #
          # If you want to deploy the python implementation, uncomment the below lines #
          # ========================================================================== #
          # build_path: ./legacy_implementation
          # dockerfile: ./legacy_implementation/Dockerfile

  deploy-dev:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: development

  deploy-uat:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: uat

  deploy-prod:
    executor: cloud-platform-executor
    steps:
      - deploy_to_environment:
          environment: production

  postman-test:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./postman/collections/Ping.postman_collection.json
          environment: ./postman/environments/${K8S_ENV}.postman_environment.json
      - newman/newman-run:
          collection: ./postman/collections/Application.postman_collection.json
          environment: ./postman/environments/${K8S_ENV}.postman_environment.json
          additional-options: --env-var="tenantId=${ENTRA_TENANT_ID}" --env-var="applicationId=${ENTRA_APP_ID}" --env-var="applicationSecret=${ENTRA_APP_SECRET}"

workflows:
  version: 2

  test-opened-pr:
    jobs:
      - lint-python-app:
          filters:
            branches:
              ignore:
                - main
      - test-python-app:
          filters:
            branches:
              ignore:
                - main
      - scan-python-docker-image:
          filters:
            branches:
              ignore:
                - main
      - lint-app:
          filters:
            branches:
              ignore:
                - main
      - test-app:
          filters:
            branches:
              ignore:
                - main
      - scan-docker-image:
          filters:
            branches:
              ignore:
                - main

  build-and-deploy-open-pr:
    jobs:
      - build-and-push:
        filters:
            branches:
              ignore:
                - main
      - deploy-dev:
          context: laa-crime-application-store-dev
          requires:
            - build-and-push

  test-build-deploy-merged-pr:
    jobs:
      - lint-python-app:
          filters:
            branches:
              only:
                - main
      - test-python-app:
          filters:
            branches:
              only:
                - main
      - scan-python-docker-image:
          filters:
            branches:
              only:
                - main
      - lint-app:
          filters:
            branches:
              only:
                - main
      - test-app:
          filters:
            branches:
              only:
                - main
      - scan-docker-image:
          filters:
            branches:
              only:
                - main
      - build-and-push:
          requires:
            - lint-python-app
            - test-python-app
            - scan-python-docker-image
            - lint-app
            - test-app
            - scan-docker-image
      - deploy-dev:
          context: laa-crime-application-store-dev
          requires:
              - build-and-push
      - postman-test:
          name: dev postman tests
          context: laa-crime-application-store-dev
          requires:
            - deploy-dev
      - deploy-uat:
          context: laa-crime-application-store-uat
          requires:
              - build-and-push
          filters:
              branches:
                  only:
                      - main
      - postman-test:
          name: uat postman tests
          context: laa-crime-application-store-uat
          requires:
            - deploy-uat
      - deploy-prod:
          context: laa-crime-application-store-prod
          filters:
              branches:
                  only:
                      - main
          requires:
           - deploy-uat

