# for ActiveRecord models
ActiveRecord::Type.register(:gbp, LaaCrimeFormsCommon::Type::Gbp)
# for ActiveModel models (models that don't persist data to DB directly)
ActiveModel::Type.register(:gbp, LaaCrimeFormsCommon::Type::Gbp)
ActiveModel::Type.register(:translated, LaaCrimeFormsCommon::Type::TranslatedObject)
ActiveModel::Type.register(:translated_array, LaaCrimeFormsCommon::Type::TranslatedObjectArray)
ActiveModel::Type.register(:time_period, LaaCrimeFormsCommon::Type::TimePeriod)
ActiveModel::Type.register(:fully_validatable_integer, LaaCrimeFormsCommon::Type::FullyValidatableInteger)
ActiveModel::Type.register(:fully_validatable_decimal, LaaCrimeFormsCommon::Type::FullyValidatableDecimal)
ActiveModel::Type.register(:string, LaaCrimeFormsCommon::Type::StrippedString)
ActiveModel::Type.register(:value_object, LaaCrimeFormsCommon::Type::ValueObject)
ActiveModel::Type.register(:multiparam_date, LaaCrimeFormsCommon::Type::MultiparamDate)
ActiveModel::Type.register(:time_period, LaaCrimeFormsCommon::Type::TimePeriod)
ActiveModel::Type.register(:gbp, LaaCrimeFormsCommon::Type::Gbp)
ActiveModel::Type.register(:fully_validatable_integer, LaaCrimeFormsCommon::Type::FullyValidatableInteger)
ActiveModel::Type.register(:fully_validatable_decimal, LaaCrimeFormsCommon::Type::FullyValidatableDecimal)
ActiveModel::Type.register(:possibly_translated_string, LaaCrimeFormsCommon::Type::PossiblyTranslatedString)
ActiveModel::Type.register(:possibly_translated_array, LaaCrimeFormsCommon::Type::PossiblyTranslatedArray)
