# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read('.ruby-version').strip

gem 'httparty'
gem 'pg'
gem 'pond'
gem 'que'
gem 'oauth2'

group :development, :test do
  gem 'byebug'
  gem 'dotenv'
end

group :test do
  gem 'rspec'
  gem 'webmock', '~> 3.23'
end
