# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(".ruby-version").strip

gem "httparty"
gem "oauth2"
gem "pg"
gem "pond"
gem "que"

group :development, :test do
  gem "byebug"
  gem "dotenv"
  gem "rubocop"
  gem "rubocop-govuk", require: false
end

group :test do
  gem "rspec"
  gem "rspec_junit_formatter", require: false
  gem "webmock", "~> 3.23"
end
