locked:
  - granted
  - expired
  - auto_grant
casework_editable:
  - submitted
  - provider_updated
provider_editable:
  - part_grant
  - rejected
  - sent_back
casework_role: "Caseworker"
provider_role: "Provider"
