# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "dev"
replicaCount:
  app: 1
  worker: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-crime-application-store-app
fullnameOverride: laa-crime-application-store-app

podAnnotations: {}

service:
  type: ClusterIP
  port: 80
  internalPort: 3000

ingress:
  enabled: true
  namespace: laa-crime-application-store-dev
  className: default
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-crime-application-store-app-laa-crime-application-store-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: main-nscc-store-dev.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - main-nscc-store-dev.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 500Mi

service_account:
  required: false
  name: laa-crime-application-store-dev-irsa

envVars:
  environment: development
  swaggerEndpoint: /docs
  authenticationRequired: True
  subscriberFailedAttemptDeletionThreshold: '100'
# This is used to configure the temporary non-RDS postgres DB
postgresql:
  enabled: true
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  auth:
    database: nsm_store_dev
    enablePostgresUser: true
    postgresPassword: postgres
    analyticsPassword: postgres
  postgresqlUsername: postgres
  analyticsUsername: analytics
  primary:
    persistence:
      enabled: true
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: [ "ALL" ]

# see https://artifacthub.io/packages/helm/bitnami/redis for parameters
redis:
  enabled: true
  architecture: standalone
  master:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: [ "ALL" ]
  auth:
    enabled: true
    password: redis

# If you want to create metabase queries pointing at a dev branch database then you can do that from the UI in UAT
metabase:
  enabled: false


