# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "prod"
replicaCount:
  app: 4
  worker: 2


image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-crime-application-store-app
fullnameOverride: laa-crime-application-store-app

podAnnotations: {}

service:
  type: ClusterIP
  port: 80
  internalPort: 3000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}

service_account:
  required: true
  name: laa-crime-application-store-production-irsa

envVars:
  environment: production
  swaggerEndpoint:
  authenticationRequired: True

# Instead of a temporary postgres pod we use RDS
postgresql:
  enabled: false

# Instead of a temporary redis pod we use Elasticache
redis:
  enabled: false

metabase:
  enabled: true
  url: "crime-forms-metabase.service.justice.gov.uk"
  image: metabase/metabase:v0.56.x
  service:
    port: 80
    internalPort: 3000
  ingress:
    namespace: laa-crime-application-store-production
    tls:
      secretName: laa-crime-application-store-cert
  warehouseDbPoolSize: "25"
  applicationDbPoolSize: "15"
  whitelist:
    enabled: true
